TSP_Django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('select2/', include('django_select2.urls'))
]

home/urls.py
from django.urls import path
from . import views



app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('user/login/', views.LoginView.as_view(), name='user_login'),
    path('user/logout/', views.LogoutView.as_view(), name='user_logout'),
    path('user/register/', views.RegisterView.as_view(), name='user_register'),

    path('add/location/', views.AddLocationView.as_view(), name='add_location'),
    path('add/session/', views.AddSessionView.as_view(), name='add_session'),
    path('add/customer/', views.AddCustomerView.as_view(), name='add_customer'),

    path('datail/session/<int:session_id>/', views.SessionDetailView.as_view(), name='session_detail'),
    path('datail/location/<int:location_id>/', views.LocationDetailView.as_view(), name='location_detail'),
    path('datail/customer/<int:customer_id>/', views.CustomerDetailView.as_view(), name='customer_detail'),

    path('list/location/', views.LocationListView.as_view(), name='location_list'),
    path('list/session/', views.SessionListView.as_view(), name='session_list'),
    path('list/customer/', views.CustomerListView.as_view(), name='customer_list'),

    path('edit/session/<int:session_id>/', views.SessionEditView.as_view(), name='session_edit'),
    path('edit/customer/<int:customer_id>/', views.CustomerEditView.as_view(), name='customer_edit'),

    path('delete/location/<int:location_id>/', views.LocationDeleteView.as_view(), name='location_delete'),
    path('delete/session/<int:session_id>/', views.SessionDeleteView.as_view(), name='session_delete'),

    path('calculation/session/<int:session_id>/', views.SessionCalculationView.as_view(), name='session_calculation'),
]

home/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Location(models.Model):
    name = models.TextField(max_length=50, null=True, blank=True, unique=True)
    latitude = models.FloatField()
    longitude = models.FloatField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.name}'
    class Meta():
        ordering = ['-created']


class Customer(models.Model):
    name = models.TextField(max_length=50)
    shop_name = models.TextField(max_length=50)
    latitude = models.FloatField()
    longitude = models.FloatField()
    address = models.TextField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.name}'


class Session(models.Model):
    name = models.TextField(max_length=50, null=True, blank=True, unique=True)
    customer = models.ManyToManyField(Customer, related_name='customers')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.name} | {self.created}'
    class Meta():
        ordering = ['-created']

home/forms.py
from django import forms
from .models import Location, Session, Customer
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django_select2.forms import Select2MultipleWidget


class UserLoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))


class LocationCreateEditForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Name of Your location'}))
    lat_lon = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'00.000000, 00.000000'}), label='Latitude, Longitude')

class CustomerCreateForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Name of Your location'}))
    shop_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Name of Your location'}))
    latitude = forms.FloatField(widget=forms.HiddenInput)
    longitude = forms.FloatField(widget=forms.HiddenInput)


class CustomerEditForm(forms.ModelForm):

    class Meta():
        model = Customer
        fields = [
            'name', 'shop_name', 'address', 'latitude', 'longitude'
        ]
        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Customer Name'}),
            'shop_name': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Name of Your Shop'}),
            'address': forms.Textarea(attrs={'class':'form-control', 'placeholder':'Your Address'}),
            'latitude': forms.TextInput(attrs={'class':'form-control', 'placeholder':'00.000000'}),
            'longitude': forms.TextInput(attrs={'class':'form-control', 'placeholder':'00.000000'}),
        }
        labels = {
            'shop_name': 'Shop Name',
        }

class SessionCreateEditForm(forms.ModelForm):

    customer = forms.ModelMultipleChoiceField(queryset=Customer.objects.all(), widget=Select2MultipleWidget(attrs={'class': 'form-control select2', 'data-placeholder': 'Select Customers...'}), required=True)

    class Meta():
        model = Session
        fields = [
            'name', 'customer'
        ]


        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Name of Your session'}),
        }

        # customer = forms.ModelMultipleChoiceField(queryset=Customer.objects.all())
        # widget = forms.SelectMultiple(attrs={'class': 'select2'})


class UserRegistrationForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))
    password_confirm = forms.CharField(label='Confirm Password', widget=forms.PasswordInput(attrs={'class':'form-control'}))

    def clean_username(self):
        username = self.cleaned_data['username']
        user = User.objects.filter(username=username).exists()
        if user:
            raise ValidationError('This Username Exists!')
        return username


















# class LocationForm(forms.ModelForm):
#     class Meta():
#         model = Location
#         fields = [
#             'name', 'latitude', 'longitude'
#             ]
#         widgets = {
#             'name': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Name of Your location'}),
#             'latitude': forms.NumberInput(attrs={'class':'form-control', 'placeholder':'00.000000'}),
#             'longitude': forms.NumberInput(attrs={'class':'form-control', 'placeholder':'00.000000'})
#         }

home/views.py
import requests, pulp, openrouteservice, numpy as np
from .forms import UserLoginForm, LocationCreateEditForm, SessionCreateEditForm, UserRegistrationForm, CustomerEditForm, CustomerCreateForm
from .models import Location, Session, Customer
from .functions import neshan_distance_matrix, neshan_cor_addr, ping
from django.shortcuts import render, redirect
from django.views import View
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.db import IntegrityError
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from requests.exceptions import RequestException, SSLError
# Create your views here.





class HomeView(LoginRequiredMixin, View):
    

    def get(self, request, *args, **kwargs):
        locations = Location.objects.all()
        customers = Customer.objects.all()
        sessions = Session.objects.all()

        if ping() == 1:
            messages.warning(request, '''Couldn't ping the services! Check Your Internet.''', 'warning')

        return render(request, 'home/index.html', {'locations':locations, 'sessions': sessions, 'customers':customers})
    

class LoginView(View):
    form_class = UserLoginForm


    def dispatch(self, request, *args, **kwargs):
        # if ping() == 1:
        #     messages.warning(request, '''Couldn't ping the services! Check Your Internet.''', 'warning')
        if request.user.is_authenticated:
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, 'home/login.html', {'form': form})
    
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd['username'], password=cd['password'])
            if user is not None:
                login(request, user)
                messages.success(request, f'Welcome {user.username}!', 'success')
                return redirect('home:home')
            messages.error(request, 'Username or Password is WRONG', 'warning')
        return render(request, 'home/login.html', {'form': form})
    

class LogoutView(LoginRequiredMixin, View):
    def get(self, request):
        urname = request.user.username
        logout(request)
        messages.success(request, f'Come Back Soon, {urname}', 'success')
        return redirect('home:home')
    

class RegisterView(View):
    form_class = UserRegistrationForm
    template_name = 'home/register.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form':form})
    
    def post(self, request):
        form=self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            User.objects.create_user(cd['username'], cd['email'], cd['password'])
            messages.success(request, f'Registered Successfully. Enjoy {cd['username']}!', 'success')
            return redirect('home:user_login')
        return render(request, self.template_name, {'form':form})

class AddLocationView(LoginRequiredMixin, PermissionRequiredMixin, View):
    class_form = LocationCreateEditForm
    permission_required = 'home.add_location'
    
    def dispatch(self, request, *args, **kwargs):
        if ping() == 1:
            messages.warning(request, '''Couldn't ping the services! Check Your Internet.''', 'warning')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        form = self.class_form()
        return render(request, 'home/add_location.html', {'form':form})
    
    def post(self, request, *args, **kwargs):
        form = self.class_form(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            name = cd['name']
            latitude = cd['lat_lon'].split(', ')[0]
            longitude = cd['lat_lon'].split(', ')[1]
            try:
                Location.objects.create(name=name, latitude=latitude, longitude=longitude)
                messages.success(request, f'{name} created successfully!')
                form = self.class_form()
            except ValueError:
                messages.error(request, 'Invalid Input', 'danger')    
        return render(request, 'home/add_location.html', {'form':form}) 
    

class AddCustomerView(LoginRequiredMixin, View):
    class_form = CustomerCreateForm
    class_template = 'home/add_customer.html'

    def dispatch(self, request, *args, **kwargs):
        if ping() == 1:
            messages.warning(request, '''Couldn't ping the services! Check Your Internet.''', 'warning')
        return super().dispatch(request, *args, **kwargs)
    
    def get(self, request, *args, **kwargs):
        form = self.class_form()
        return render(request, self.class_template, {'form': form})
    
    def post(self, request, *args, **kwargs):
        form = self.class_form(request.POST)
        print(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            name = cd['name']
            latitude = cd['latitude']
            longitude = cd['longitude']
            shop_name = cd['shop_name']
            try:
                address = neshan_cor_addr(lat=latitude, lon=longitude)
            except requests.exceptions.RequestException:
                address = 'Null'
                messages.error(request, '''Due to connection Failure, default address was set to 'Null'! ''', 'warning')
            try:
                Customer.objects.create(name=name, latitude=latitude, longitude=longitude, shop_name=shop_name, address=address)
                messages.success(request, f'{name} created successfully!')
                form = self.class_form()
            except ValueError:
                messages.error(request, 'Invalid Input', 'danger')    
        return render(request, self.class_template, {'form':form}) 
 

class CustomerDetailView(View):
    def get(self, request, *args, **kwargs):
        customer = get_object_or_404(Customer, pk=kwargs['customer_id'])
        for_map = []
        for_map_lib = {}
        for_map_lib['name'] = customer.name
        for_map_lib['lat'] = customer.latitude
        for_map_lib['lng'] = customer.longitude
        for_map.append(for_map_lib)

        return render(request, 'home/customer_detail.html', {'customer': customer, 'for_map': for_map})


class CustomerEditView(View):
    class_form = CustomerEditForm
    class_template = 'home/customer_edit.html'

    def setup(self, request, *args, **kwargs):
        self.customer_instance = Customer.objects.get(pk=kwargs['customer_id'])
        return super().setup(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        customer = self.customer_instance
        form = self.class_form(instance=customer)
        return render(request, self.class_template, {'form': form, 'customer': customer})
    
    def post(self, request, *args, **kwargs):
        customer = self.customer_instance
        form = self.class_form(request.POST, instance=customer)
        if form.is_valid():
            form.save()
            messages.success(request, 'Customer Edited Successfully!', 'success')
            return redirect('home:customer_detail', customer.id)
        messages.error(request, 'Invalid Input!', 'danger')
        return redirect('home:customer_detail', customer.id)


class LocationDetailView(View):
    def get(self, request, *args, **kwargs):
        loc = Location.objects.get(pk=kwargs['location_id'])
        for_map = []
        for_map_lib = {}
        for_map_lib['name'] = loc.name
        for_map_lib['lat'] = loc.latitude
        for_map_lib['lng'] = loc.longitude
        for_map.append(for_map_lib)

        if ping('8.8.8.8') == 1:
            messages.warning(request, '''Couldn't ping the services! Check Your Internet.''', 'warning')

        return render(request, 'home/location_detail.html', {'loc': loc, 'for_map': for_map})
    

class LocationListView(View):
    def get(self, request, *args, **kwargs):
        locations = Location.objects.all()
        return render(request, 'home/location_list.html', {'locations': locations})


class SessionListView(View):
    def get(self, request, *args, **kwargs):
        sessions = Session.objects.all()
        return render(request, 'home/location_list.html', {'sessions': sessions})


class CustomerListView(View):
    def get(self, request, *args, **kwargs):
        customers = Customer.objects.all()
        return render(request, 'home/location_list.html', {'customers': customers})


class LocationDeleteView(View):

    def get(self, request, *args, **kwargs):
        location = Location.objects.get(pk=kwargs['location_id'])
        location_name = location.name
        location.delete()
        messages.success(request, f'''Location "{location_name}" deleted successfully!''', 'success')
        return redirect('home:home')


class AddSessionView(LoginRequiredMixin, View):
    class_form = SessionCreateEditForm
    def get(self, request, *args, **kwargs):
        form = self.class_form()
        return render(request, 'home/add_session.html', {'form': form})
    
    def post(self, request, *args, **kwargs0):
        form = self.class_form(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            name = cd['name']
            form.save()
            messages.success(request, f'{name} added to sessions')
        return redirect('home:home')
    

class SessionDetailView(LoginRequiredMixin, View):

home/templates/home/add_customer.html
{% extends "base.html" %}
{% block content %}
    <h3 class='text-center'>Add Customer</h3>
    <hr>

    <form acion='' method='POST' class='col-md-2 offset-lg-5' novalidate>
        <div class='row'>
            {% csrf_token %}
            {{ form.as_p }}
            <input type="hidden" class="form-control" id="latitude" name="latitude" readonly>
            <input type="hidden" class="form-control" id="longitude" name="longitude" readonly>
            <span class="input-group-btn">
                <input class="btn btn-outline-success col-md-4 offset-lg-4" type="submit" value="Submit">
            </span>
        </div>
    </form>

    <div align="center">
        <div id="map"></div>
        <!-- Leaflet JavaScript -->
        <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>


        <script>

            // Initialize the map
            const map = L.map('map').setView([36.322217000498554, 59.57129235510297], 11); // Set initial view (latitude, longitude, zoom level)

            // Add OpenStreetMap tiles
            L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
                attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
            }).addTo(map);
            
            let marker;
            map.on('click', function(e) {
                const { lat, lng } = e.latlng;

                if (marker) {
                    map.removeLayer(marker);
                }
                marker = L.marker([lat, lng]).addTo(map);
                document.getElementById('latitude').value = lat;
                document.getElementById('longitude').value = lng;
            })
        </script>
    </div>
{% endblock content %}

home/templates/home/add_location.html
{% extends "base.html" %}
{% block content %}
    <h3 class='text-center'>Add Location</h3>
    <hr>

    <form acion='' method='POST' class='col-md-2 offset-lg-5' novalidate>
        <div class='row'>
            {% csrf_token %}
            {{ form.as_p }}
            <span class="input-group-btn">
                <input class="btn btn-outline-success col-md-4 offset-lg-4" type="submit" value="Submit">
            </span>
        </div>
    </form>
{% endblock content %}

home/templates/home/add_session.html
{% extends "base.html" %}


{% block content %}
    <h3 class='text-center'>Add Session</h3>
    <hr>



    <form acion='' method='POST' class='col-md-2 offset-lg-5' novalidate>
        <div class='row'>
            {% csrf_token %}
            {{ form.media }}
            {{ form.as_p }}
            <span class="input-group-btn">
                <input class="btn btn-outline-success col-md-4 offset-lg-4" type="submit" value="Submit">
            </span>
        </div>
    </form>


{% endblock content %}

home/templates/home/customer_list.html
{% extends "base.html" %}
{% block content %}
{% for cus in customers %}
    <a href='{% url 'home:customer_detail' cus.id %}'>{{ cus.name }}</a>
    <hr>
{% endfor %}
{% endblock content %}

home/templates/home/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <h3 class='text-center'>TSP Solver By Imiza</h3>
  <hr>
  
    <div class='row'>
      <div class='col-sm-6'>
        <div class="card" style="width: 38rem;">
          <img class="card-img-top" src="{% static "home/images/add_location.jpg" %}" alt="Location">
          <div class="card-body">
            <h5 class="card-title">Add Customer</h5>
            <p class="card-text">Here You can add new locations to use in your TSP sessions later. only the latitude and longitude of the locations is neede</p>
            <a href="{% url 'home:add_customer' %}" class="btn btn-outline-primary col-md-4 offset-lg-4">Add</a>
          </div>
        </div>
      </div>
      <div class='col-sm-6'>
        <div class="card" style="width: 38rem;">
          <img class="card-img-top" src="{% static "home/images/add_session.jpg" %}" alt="Session">
          <div class="card-body">
            <h5 class="card-title">Add Session</h5>
            <p class="card-text">Create diffrent sessions including as many locations needed and see the TSP answer anytime.</p>
            <a href="{% url 'home:add_session' %}" class="btn btn-outline-primary col-md-4 offset-lg-4">Add</a>
          </div>
        </div>
      </div>
    </div>
    <hr>
    <div class='row'>
      <div class='col-sm-6'>
        <div class="card bg-dark text-white" style="width: 38rem;">
          <div class="card-body">
            <h5 class="card-title">All Customers</h5>
            {% for customer in customers %}
              <a href="{% url 'home:customer_detail' customer.id%}" class="btn btn-outline-light col-md-4 offset-lg-4 text-white">{{customer.name}}</a>
              <hr>
            {% endfor %}
          </div>
        </div>
      </div>
      <div class='col-sm-6'>
        <div class="card bg-dark text-white" style="width: 38rem;">
          <div class="card-body">
            <h5 class="card-title">All Sessions</h5>
            {% for session in sessions %}
              <a href="{% url 'home:session_detail' session.id %}" class="btn btn-outline-light col-md-4 offset-lg-4 text-white">{{session.name}}</a>
              <hr>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
    <hr>
    <a href='{% url 'home:location_list' %}'>Locations</a>
    <a href='{% url 'home:session_list' %}'>Sessions</a>
    <a href='{% url 'home:customer_list' %}'>Customers</a>
{% endblock content %}

home/templates/home/location_detail.html
{% extends "base.html" %}
{% block content %}
    <h3 class='text-center'>
        {{ loc.name }}
    </h3>
    <a href='{% url 'home:location_delete' loc.id %}' class='btn btn-danger btn-md'>Delete</a> 
    {% comment %} <a href='{% url 'home:location_delete' loc.id %}' class='btn btn-danger col-md-1'>Delete</a>  {% endcomment %}
    <hr>
    <div align="center">
        <div id="map"></div>
        <!-- Leaflet JavaScript -->
        <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>

        <!-- Embed for_map data using json_script -->
        {{ for_map|json_script:"for-map-data" }}

        <script>
            // Retrieve the for_map data from the script tag
            const forMap = JSON.parse(document.getElementById('for-map-data').textContent);
            console.log(forMap); // Debugging: Log the data

            // Initialize the map
            const map = L.map('map').setView([36.31713072459344, 59.56093492310713], 1); // Set initial view (latitude, longitude, zoom level)

            // Add OpenStreetMap tiles
            L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
                attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
            }).addTo(map);

            // Add markers for each location
            forMap.forEach(loc => {
                console.log(`Adding marker at ${loc.lat}, ${loc.lng}`); // Debugging: Log each marker
                L.marker([loc.lat, loc.lng])
                    .addTo(map)
                    .bindPopup(loc.name); // Add a popup with the location name
            });
        </script>
    </div>

{% endblock content %}

home/templates/home/location_edit.html
{% extends "base.html" %}
{% block content %}

Location Edit

<form acion='' method='POST' class='col-md-2 offset-lg-5' novalidate>
    <div class='row'>
        {% csrf_token %}
        {{ form.as_p }}
        <span class="input-group-btn">
            <input class="btn btn-outline-success col-md-4 offset-lg-4" type="submit" value="Submit">
        </span>
    </div>
</form>


{% endblock content %}

home/templates/home/location_list.html
{% extends "base.html" %}
{% block content %}
{% for loc in locations %}
    <a href='{% url 'home:location_detail' loc.id %}'>{{ loc.name }}</a>
    <hr>
{% endfor %}
{% endblock content %}

home/templates/home/login.html
{% extends "base.html" %}
{% block content %}
<h3 class='text-center'>Login</h3>
<hr>
    <form acion='' method='POST' class='col-md-2 offset-lg-5' novalidate>
        <div class='row'>
            {% csrf_token %}
            {{ form.as_p }}
            <span class="input-group-btn">
                <input class="btn btn-outline-success col-md-4 offset-lg-4" type="submit" value="Login">
            </span>
            <br>
        </div>
    </form>
    <a href='{% url 'home:user_register' %}' class='text-center'>Don't have an account?</a>
{% endblock content %}

home/templates/home/register.html
{% extends "base.html" %}
{% block content %}

<h3 class='text-center'>User Register</h3>
<hr>
    <form acion='' method='POST' class='col-md-2 offset-lg-5' novalidate>
        <div class='row'>
            {% csrf_token %}
            {{ form.as_p }}
            <span class="input-group-btn">
                <input class="btn btn-outline-success col-md-4 offset-lg-4" type="submit" value="Register">
            </span>
        </div>
    </form>

{% endblock content %}

home/templates/home/session_detail.html
{% extends "base.html" %}
{% block content %}

    <h3>{{ session.name }}</h3>
    <a href='{% url 'home:session_edit' session.id %}' class='btn btn-primary btn-md'>Edit</a> 
    <a href='{% url 'home:session_delete' session.id %}' class='btn btn-danger btn-md'>Delete</a> 
    <hr>
    {% for location in customers %}
        {{ forloop.counter }}: {{ location.name }}
        <br>
    {% endfor %}
    <a href="{% url 'home:session_calculation' session.id %}" class="btn btn-dark col-md-4 offset-lg-4">TSP Answer</a>
{% endblock content %}

home/templates/home/session_edit.html
{% extends "base.html" %}

{% block content %}
<h3 class='text-center'>Edit <b>"{{session.name}}"</b> Session</h3>
<hr>


<form acion='' method='POST' class='col-md-2 offset-lg-5' novalidate>
    <div class='row'>
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
        <span class="input-group-btn">
            <input class="btn btn-success col-md-4 offset-lg-4" type="submit" value="Edit">
        </span>
    </div>
</form>

{% endblock content %}

home/templates/home/session_list.html
{% extends "base.html" %}
{% block content %}
{% for ses in sessions %}
    <a href='{% url 'home:session_detail' ses.id %}'>{{ ses.name }}:</a>
    <hr>
{% endfor %}
{% endblock content %}

home/templates/home/tsp_solved.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <h3 class='text-center'>Most officient Route is the following:</h3>
    <hr>
    {% for r in ordered_route %}
        <h4 class='text-center'>{{ r }}</h4> 
    {% endfor %}
    <hr>
    <div align="center">
        <div id="map"></div>
        <!-- Leaflet JavaScript -->
        <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>

        <!-- Embed for_map data using json_script -->
        {{ for_map|json_script:"for-map-data" }}

        <script>
            // Retrieve the for_map data from the script tag
            const forMap = JSON.parse(document.getElementById('for-map-data').textContent);
            console.log(forMap); // Debugging: Log the data

            // Initialize the map
            const map = L.map('map').setView([36.322217000498554, 59.57129235510297], 11); // Set initial view (latitude, longitude, zoom level)

            // Add OpenStreetMap tiles
            L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
                attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
            }).addTo(map);

            // Add markers for each location
            forMap.forEach((loc, index)=> {
                console.log(`Adding marker at ${loc.lat}, ${loc.lng}`); // Debugging: Log each marker
                L.marker([loc.lat, loc.lng])
                    .addTo(map)
                    .bindTooltip(`${index + 1}. ${loc.name}`, { permanent: true, direction: 'top' });
            });
        </script>
    </div>
    <hr>
    <div align="center">
        <b>Location Number Guid:</b>
        <br>
        {% for l in for_map %}
            <span><b>{{ forloop.counter }}:</b> {{ l.name }}, </span> 
        {% endfor %}
    </div>
{% endblock content %}