TSP_Django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('select2/', include('django_select2.urls'))
]

home/urls.py
from django.urls import path
from . import views



app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('user/login/', views.LoginView.as_view(), name='user_login'),
    path('user/logout/', views.LogoutView.as_view(), name='user_logout'),
    path('user/register/', views.RegisterView.as_view(), name='user_register'),

    path('add/location/', views.AddLocationView.as_view(), name='add_location'),
    path('add/session/', views.AddSessionView.as_view(), name='add_session'),
    path('add/customer/', views.AddCustomerView.as_view(), name='add_customer'),

    path('datail/session/<int:session_id>/', views.SessionDetailView.as_view(), name='session_detail'),
    path('datail/location/<int:location_id>/', views.LocationDetailView.as_view(), name='location_detail'),
    path('datail/customer/<int:customer_id>/', views.CustomerDetailView.as_view(), name='customer_detail'),

    path('list/location/', views.LocationListView.as_view(), name='location_list'),
    path('list/session/', views.SessionListView.as_view(), name='session_list'),
    path('list/customer/', views.CustomerListView.as_view(), name='customer_list'),

    path('edit/session/<int:session_id>/', views.SessionEditView.as_view(), name='session_edit'),
    path('edit/customer/<int:customer_id>/', views.CustomerEditView.as_view(), name='customer_edit'),

    path('delete/location/<int:location_id>/', views.LocationDeleteView.as_view(), name='location_delete'),
    path('delete/session/<int:session_id>/', views.SessionDeleteView.as_view(), name='session_delete'),

    path('calculation/session/<int:session_id>/', views.SessionCalculationView.as_view(), name='session_calculation'),
]

templates/incs/messages.html
{% if messages %}
    
    {% for msg in messages %}
        <p class='alert alert-{{ msg.tags }} col-md-4 ' > {{msg}} </p>
    {% endfor %}

{% endif %}

templates/incs/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <div class="navbar-nav">
        {% comment %} <a class="navbar-brand text-center" href="{% url "home:home" %}">TSP by imiza</a>

        {% if request.user.is_authenticated %}
            <a class="navbar-brand" href="{% url "home:user_logout" %}">Logout</a>
        {% endif %} {% endcomment %}


        {% if request.user.is_authenticated %}
            <a class="navbar-brand" href="{% url "home:home"  %}">Home</a>
            <a class="navbar-brand" href="{% url "home:user_logout" %}">Logout</a>
            {% if request.user.username == 'root' %}
              <a class="navbar-brand" href="/admin/">Admin</a>
            {% endif %}
        {% comment %} {% else %}
            <a class="navbar-brand" href="{% url "" %}">Register</a>
            <a class="navbar-brand" href="{% url "" %}">Login</a> {% endcomment %}
        {% endif %}
      </div>
    </div>
  </nav>